package org.ai.order.dao;

import java.util.List;
import org.ai.order.model.Order;
import org.ai.order.model.OrderExample;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eorder
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);
}