package org.ai.order.dao;

import java.util.List;
import org.ai.order.model.UserPermission;
import org.ai.order.model.UserPermissionExample;

public interface UserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int countByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int deleteByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insert(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insertSelective(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    List<UserPermission> selectByExampleWithBLOBs(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    List<UserPermission> selectByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    UserPermission selectByPrimaryKey(Integer id);

    UserPermission selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExampleSelective(UserPermission record, UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExampleWithBLOBs(UserPermission record, UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExample(UserPermission record, UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByPrimaryKeySelective(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user_permission
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByPrimaryKey(UserPermission record);
}