package org.ai.order.dao;

import java.util.List;

import org.ai.order.model.User;
import org.ai.order.model.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    User selectByPrimaryKey(Integer id);

    User selectByUserName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExampleSelective(User record, UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByExample(User record, UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_user
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    int updateByPrimaryKey(User record);
}