package org.ai.order.model;

import java.util.Date;

public class BlackEyeSum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_eye_sum.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_eye_sum.PAGE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_eye_sum.RECORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_eye_sum.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_eye_sum.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_eye_sum.ID
     *
     * @return the value of black_eye_sum.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_eye_sum.ID
     *
     * @param id the value for black_eye_sum.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_eye_sum.PAGE
     *
     * @return the value of black_eye_sum.PAGE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_eye_sum.PAGE
     *
     * @param page the value for black_eye_sum.PAGE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_eye_sum.RECORD
     *
     * @return the value of black_eye_sum.RECORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_eye_sum.RECORD
     *
     * @param record the value for black_eye_sum.RECORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setRecord(Integer record) {
        this.record = record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_eye_sum.UPDATED_DATE
     *
     * @return the value of black_eye_sum.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_eye_sum.UPDATED_DATE
     *
     * @param updatedDate the value for black_eye_sum.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_eye_sum.CREATED_DATE
     *
     * @return the value of black_eye_sum.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_eye_sum.CREATED_DATE
     *
     * @param createdDate the value for black_eye_sum.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}