package org.ai.order.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.ORDER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.QUANTITY
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.PRICE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.RECIEVER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String recieverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.RECIEVER_ADDRESS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String recieverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.RECIEVER_PHONE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String recieverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.PAY_METHOD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.EXPRESS_SATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String expressSatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.ORDER_STATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.ORDER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String orderIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.ORDER_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.OTHERS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.COMMENTS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eorder.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.ID
     *
     * @return the value of eorder.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.ID
     *
     * @param id the value for eorder.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.ORDER_NAME
     *
     * @return the value of eorder.ORDER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.ORDER_NAME
     *
     * @param orderName the value for eorder.ORDER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.QUANTITY
     *
     * @return the value of eorder.QUANTITY
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.QUANTITY
     *
     * @param quantity the value for eorder.QUANTITY
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.PRICE
     *
     * @return the value of eorder.PRICE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.PRICE
     *
     * @param price the value for eorder.PRICE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.RECIEVER_NAME
     *
     * @return the value of eorder.RECIEVER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getRecieverName() {
        return recieverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.RECIEVER_NAME
     *
     * @param recieverName the value for eorder.RECIEVER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setRecieverName(String recieverName) {
        this.recieverName = recieverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.RECIEVER_ADDRESS
     *
     * @return the value of eorder.RECIEVER_ADDRESS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getRecieverAddress() {
        return recieverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.RECIEVER_ADDRESS
     *
     * @param recieverAddress the value for eorder.RECIEVER_ADDRESS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setRecieverAddress(String recieverAddress) {
        this.recieverAddress = recieverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.RECIEVER_PHONE
     *
     * @return the value of eorder.RECIEVER_PHONE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getRecieverPhone() {
        return recieverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.RECIEVER_PHONE
     *
     * @param recieverPhone the value for eorder.RECIEVER_PHONE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setRecieverPhone(String recieverPhone) {
        this.recieverPhone = recieverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.PAY_METHOD
     *
     * @return the value of eorder.PAY_METHOD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.PAY_METHOD
     *
     * @param payMethod the value for eorder.PAY_METHOD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.EXPRESS_SATUS
     *
     * @return the value of eorder.EXPRESS_SATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getExpressSatus() {
        return expressSatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.EXPRESS_SATUS
     *
     * @param expressSatus the value for eorder.EXPRESS_SATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setExpressSatus(String expressSatus) {
        this.expressSatus = expressSatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.ORDER_STATUS
     *
     * @return the value of eorder.ORDER_STATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.ORDER_STATUS
     *
     * @param orderStatus the value for eorder.ORDER_STATUS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.ORDER_ID
     *
     * @return the value of eorder.ORDER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getOrderIp() {
        return orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.ORDER_ID
     *
     * @param orderIp the value for eorder.ORDER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.ORDER_DATE
     *
     * @return the value of eorder.ORDER_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.ORDER_DATE
     *
     * @param orderDate the value for eorder.ORDER_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.OTHERS
     *
     * @return the value of eorder.OTHERS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.OTHERS
     *
     * @param others the value for eorder.OTHERS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setOthers(String others) {
        this.others = others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.COMMENTS
     *
     * @return the value of eorder.COMMENTS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.COMMENTS
     *
     * @param comments the value for eorder.COMMENTS
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.UPDATED_DATE
     *
     * @return the value of eorder.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.UPDATED_DATE
     *
     * @param updatedDate the value for eorder.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eorder.CREATED_DATE
     *
     * @return the value of eorder.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eorder.CREATED_DATE
     *
     * @param createdDate the value for eorder.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}