package org.ai.order.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.USER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.PASSWORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.ID
     *
     * @return the value of order_user.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.ID
     *
     * @param id the value for order_user.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.USER_NAME
     *
     * @return the value of order_user.USER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.USER_NAME
     *
     * @param userName the value for order_user.USER_NAME
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.PASSWORD
     *
     * @return the value of order_user.PASSWORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.PASSWORD
     *
     * @param password the value for order_user.PASSWORD
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.UPDATED_DATE
     *
     * @return the value of order_user.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.UPDATED_DATE
     *
     * @param updatedDate the value for order_user.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.CREATED_DATE
     *
     * @return the value of order_user.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.CREATED_DATE
     *
     * @param createdDate the value for order_user.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}