package org.ai.order.model;

import java.util.Date;

public class UserPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user_permission.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user_permission.USER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user_permission.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user_permission.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user_permission.USER_PERMISSION
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    private byte[] userPermission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user_permission.ID
     *
     * @return the value of order_user_permission.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user_permission.ID
     *
     * @param id the value for order_user_permission.ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user_permission.USER_ID
     *
     * @return the value of order_user_permission.USER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user_permission.USER_ID
     *
     * @param userId the value for order_user_permission.USER_ID
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user_permission.UPDATED_DATE
     *
     * @return the value of order_user_permission.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user_permission.UPDATED_DATE
     *
     * @param updatedDate the value for order_user_permission.UPDATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user_permission.CREATED_DATE
     *
     * @return the value of order_user_permission.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user_permission.CREATED_DATE
     *
     * @param createdDate the value for order_user_permission.CREATED_DATE
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user_permission.USER_PERMISSION
     *
     * @return the value of order_user_permission.USER_PERMISSION
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public byte[] getUserPermission() {
        return userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user_permission.USER_PERMISSION
     *
     * @param userPermission the value for order_user_permission.USER_PERMISSION
     *
     * @mbggenerated Tue Apr 19 22:13:12 CST 2016
     */
    public void setUserPermission(byte[] userPermission) {
        this.userPermission = userPermission;
    }
}